# Generated by Django 6.0 on 2025-12-22 08:34

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension()
    ]
