# Generated by Django 6.0 on 2025-12-11 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='context_window_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='ollama_model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='corp.agent'),
        ),
    ]
