# Generated by Django 6.0 on 2025-12-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='allowed_tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
