# Generated by Django 6.0 on 2025-12-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0003_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('THINKING', 'Thinking'), ('WAIT_SUBTASK', 'Waiting for Subtasks'), ('WAIT_APPROVAL', 'Wait Approval'), ('APPROVED', 'Approved'), ('DONE', 'Done'), ('REJECTED', 'Rejected')], default='TODO', max_length=20),
        ),
    ]
