# Generated by Django 6.0 on 2026-07-24 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0003_agent_allowed_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('THINKING', 'Thinking'), ('WAIT_SUBTASK', 'Waiting for Subtasks'), ('WAIT_APPROVAL', 'Wait Approval'), ('WAIT_ANSWER', 'Waiting for Answer'), ('APPROVED', 'Approved'), ('DONE', 'Done'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated to CoS')], default='TODO', max_length=20),
        ),
        migrations.CreateModel(
            name='GatekeeperRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('FINANCIAL', 'Financial Commitment'), ('DEPLOYMENT', 'Code / System Deployment'), ('HIERARCHY_CHANGE', 'Hierarchy Alteration'), ('HIGH_RISK_TOOL', 'High Risk Tool Call')], default='HIGH_RISK_TOOL', max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending CEO Approval'), ('APPROVED', 'Approved by CEO'), ('REJECTED', 'Rejected by CEO')], default='PENDING', max_length=20)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp.agent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatekeeper_requests', to='corp.task')),
            ],
        ),
        migrations.CreateModel(
            name='ImmutableAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_digest', models.TextField()),
                ('response_digest', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_hash', models.CharField(default='GENESIS', max_length=64)),
                ('current_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='corp.agent')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='corp.task')),
            ],
        ),
    ]
