# Generated by Django 6.0 on 2025-12-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0006_announcement_channel_channelmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='can_hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='depth',
            field=models.IntegerField(default=0),
        ),
    ]
