# Generated by Django 6.0 on 2025-12-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0007_agent_can_fire_agent_can_hire_agent_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('THINKING', 'Thinking'), ('WAIT_SUBTASK', 'Waiting for Subtasks'), ('WAIT_APPROVAL', 'Wait Approval'), ('WAIT_ANSWER', 'Waiting for Answer'), ('APPROVED', 'Approved'), ('DONE', 'Done'), ('REJECTED', 'Rejected')], default='TODO', max_length=20),
        ),
    ]
